# the pipeline itself to provision controllers and load generators (typically as Docker containers), attaching them to NeoLoad Web temporarily, running the test, then disposing of the containers
trigger: none

pool:
  vmImage: 'ubuntu-16.04'
parameters:
- name: neoloadApiUrl
  type: string
  default: 'https://neoload-api.saas.neotys.com/'

variables:
  nlw_token: $(secret_nlw_token)
  zone_code: $(NLzone_code)
  PYTHONUNBUFFERED: 1

# create sidecar containers, attach them to a zone; provide supply this pipeline demands
resources:
  containers:
  - container: neoload_ctrl
    image: neotys/neoload-controller:latest
    env: { MODE: Managed, NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code) }
  - container: lg1
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code), LG_HOST=lg1, LG_PORT=7101, AGENT_SERVER_PORT=7101 }
  - container: lg2
    image: neotys/neoload-loadgenerator:latest
    env: { NEOLOADWEB_TOKEN: $(nlw_token), ZONE: $(zone_code), LG_HOST=lg2, LG_PORT=7102, AGENT_SERVER_PORT=7102 }

jobs:
- job: RunLoadTest
  displayName: Run NeoLoad Test
  services:
    neoload_ctrl: neoload_ctrl
    lg1: lg1
    lg2: lg2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'

  - task: Bash@3
    displayName: Install NeoLoad
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        pip install neoload
        neoload --version --profile docker --token $(nlw_token) --zone $(zone_code)
        neoload --help
  - task: Bash@3
    displayName: Run NeoLoad Test
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: |
        neoload --help
        cd $(Build.SourcesDirectory)
        neoload --scenario AsCodeStandalone \
                -f default.yaml \
                --testname "Azure_Jpet_$(Build.BuildNumber)" \
                --testdesc "Azure example load test with ; $(Builjpetd.BuildUri)" \
                --attach zone#2 \
                --profile docker --token $(nlw_token) --zone $(zone_code) \
                --junitsla $(Common.TestResultsDirectory)/neoload-slas.xml

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
      failTaskOnFailedTests: true